//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EmbeddedGUI.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_EmbeddedGUITYPE             129
#define ID_GRAPHICFUNCTION_DRAWHORIZONLINE 32771
#define ID_GRAPHICFUNCTION_DRAWVERTICALLINE 32772
#define ID_GRAPHICFUNCTION_DRAWLINE     32773
#define ID_GRAPHICFUNCTION_DRAWCIRCLE   32774
#define ID_GRAPHICFUNCTION_DRAWFILLEDCIRCLE 32775
#define ID_GRAPHICFUNCTION_DR           32776
#define ID_GRAPHICFUNCTION_DRAWFILLEDRECTANGLE 32777
#define ID_CONTROL_Label                32778
#define ID_CONTROL_EXTLabel             32779
#define ID_CONTROL_BUTTON               32780
#define ID_CONTROL_EDIT                 32781
#define ID_CONTROL_COMBOBOX             32782
#define ID_CONTROL_CHECKBUTTON          32783
#define ID_CONTROL_PROGRESS             32784
#define ID_WINDOW_PLAINWINDOW           32785
#define ID_WINDOW_WINDOW                32786
#define ID_DESKTOP                      32787
#define ID_DESKTOP_CLEARSCREEN          32788
#define ID_Menu                         32789
#define ID_GRAPHICFUNCTION_DRAWSTRING   32791
#define ID_GRAPHICFUNCTION_DRAWFONTSTRING 32792
#define ID_GRAPHICFUNCTION_DRAWIMAGE    32793
#define ID_DESKTOP_MESSAGEBOXINDESKTOP  32794
#define ID_DESKTOP_DIALOGBOXINDESKTOP   32795
#define ID_DESKTOP_NEWDESKTOP2          32796
#define ID_DESKTOP_ELISTINDESKTOP       32797
#define ID_DESKTOP_EMENUINDESKTOP       32798
#define ID_DESKTOP_EPOPMENUINDESKTOP    32799
#define ID_CONTROL_TREE                 32800
#define ID_DESKTOP_ETREEINDESKTOP       32801
#define ID_CONTROL_ICONBUTTON           32802
#define ID_GRAPHICFUNCTION_DRAWWIDTHLINE 32803
#define ID_GRAPHICFUNCTION_DRAWQUARTERARC 32804
#define ID_GRAPHICFUNCTION_DRAWARC      32805
#define ID_GRAPHICFUNCTION_DRAWPIESLICE 32806
#define ID_GRAPHICFUNCTION_DRAWELLIPSE  32807
#define ID_GRAPHICFUNCTION_DRAWFILLEDELLIPSE 32808
#define ID_DESKTOP_ETOOLBARINDESKTOP    32809
#define ID_CONTROL_STATUSBAR            32810
#define ID_DESKTOP_NEWDESKTOP3          32811
#define ID_DESKTOP_CHANGEDESKTOP3STATE  32812
#define ID_DESKTOP_MOVEDESKTOP3         32813
#define ID_DESKTOP_EBARCHARTINDESKTOP   32814
#define ID_CONTROL_CLOCK                32815

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32816
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
